#!/bin/sh
echo "Checking Lua scripts..."
find . -name "*.lua" \
| while read s
do
        if ! luac -p "$s" 2>/dev/null; then
                echo "$s is invalid."
        fi
done
echo "Script check completed."