function event_say(e)
	if(e.message:findi("hail")) then
		e.self:Say("Greetings, " .. e.other:GetCleanName() .. ". I am Dralin K'Vekn. Several hundred years ago I was the Teir'Dal ambassador to the Combine Empire under Tsaph Katta. I was present when the traitorous Seru made his assassination attempt on Tsaph Katta and divided the Combine Empire into the two factions that exist to this day. I was forced to flee to Luclin with the Loyalist Combine in order to escape death at the hands of the [Inquisition]. Adjusting to a new life on Luclin with no others of my kind was a long, perilous, and often times lonely task. I do not regret it though, I have a beautiful wife and a healthy son now and this place is my home and the [Loyalists] my people.");
	elseif(e.message:findi("Inquisition")) then
		e.self:Say("The followers of Seru that split from the Combine Empire have become known as the Inquisition. They were opposed, to among other things, diplomatic negotiations with Neriak. Obviously if the aftermath of the attempted assassination on Tsaph Katta had gone differently I would have been among Serus assassins next targets. Seru would have went to war with Neriak, Oggok, and Grobb in his fanatical obsession to utterly destroy all civilizations that hold values, morals, and creeds different than his own. Fortunately in his power madness to control all of the Combine Empire Seru followed us through the portal to Luclin and a second Age of Blood was narrowly avoided.");
	elseif(e.message:findi("loyalists")) then
		e.self:Say("Those of the Combine Empire that remained loyal to Tsaph Kattas teachings, philosophies, and ideals have become known as the Loyalists. When we were forced to flee to Luclin to prevent the bloodshed desired by the Inquisition we arrived deep at the core of the moon, at the location that is now Shadow Haven. We left behind a few of our numbers to watch the portal from Norrath and to discover a means to return home. The rest of us set out to explore the tunnel systems and made our way to the surface here on the dark side. It was decided we would settle on the cliffs overlooking the Twilight Sea and a great wall was erected to protect us from the strange natives of Luclin while we built our [new homes].");
	elseif(e.message:findi("new home")) then
		e.self:Say(" As you can see we have been here for quite some time and only myself and a handful of other longed lived individuals have ever seen life on Norrath. To the humans of this city and the majority of the demi-humans as well, Luclin and Katta Castellum are the only homes they know.");
	end
end
